#!/bin/sh
pdflatex -draftmode --shell-escape -file-line-error MyThesis
biber MyThesis
pdflatex -draftmode --shell-escape -interaction=batchmode -file-line-error MyThesis
pdflatex --shell-escape -interaction=batchmode -file-line-error -synctex=1 MyThesis
#latexmk -f -pdf  -latexoption='--shell-escape -interaction=nonstopmode %O %S -file-line-error -synctex=1' -latex=pdflatex ./MyThesis.tex
#gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.7 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=output.pdf MyThesis.pdf
#rm MyThesis.pdf
#mv output.pdf MyThesis.pdf
#latexmk -c
