{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Aug 22 00:45:15 2017) by ROOT version5.34/26
   TCanvas *c1 = new TCanvas("c1", "c1");
   gStyle->SetPaperSize(10.,10.);
   gStyle->SetOptStat(10);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   
   TH1F *hSetupName = new TH1F("hSetupName","Config Setup Used",21,0,21);
   hSetupName->SetBinContent(1,57);
   hSetupName->SetBinContent(2,40);
   hSetupName->SetBinContent(3,30);
   hSetupName->SetBinContent(4,14);
   hSetupName->SetBinContent(5,8);
   hSetupName->SetBinContent(6,8);
   hSetupName->SetBinContent(7,4);
   hSetupName->SetBinContent(8,3);
   hSetupName->SetBinContent(9,3);
   hSetupName->SetBinContent(10,2);
   hSetupName->SetBinContent(11,2);
   hSetupName->SetBinContent(12,2);
   hSetupName->SetBinContent(13,2);
   hSetupName->SetBinContent(14,1);
   hSetupName->SetBinContent(15,1);
   hSetupName->SetBinContent(16,1);
   hSetupName->SetBinContent(17,1);
   hSetupName->SetBinContent(18,1);
   hSetupName->SetBinContent(19,1);
   hSetupName->SetBinContent(20,1);
   hSetupName->SetBinContent(21,1);
   hSetupName->SetEntries(183);
   hSetupName->SetFillColor(38);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hSetupName->SetLineColor(ci);
   hSetupName->GetXaxis()->SetBinLabel(1,"UnknownConfig");
   hSetupName->GetXaxis()->SetBinLabel(2,"GIFPP_STRIP_22");
   hSetupName->GetXaxis()->SetBinLabel(3,"GIFPP_OYONAX_8");
   hSetupName->GetXaxis()->SetBinLabel(4,"GIFPP_OYONAX_12");
   hSetupName->GetXaxis()->SetBinLabel(5,"GIFPP_STRIP_12");
   hSetupName->GetXaxis()->SetBinLabel(6,"GIFPP_STRIP_11");
   hSetupName->GetXaxis()->SetBinLabel(7,"GIFPP_STRIP_26");
   hSetupName->GetXaxis()->SetBinLabel(8,"GIFPP_STRIP_13");
   hSetupName->GetXaxis()->SetBinLabel(9,"GIFPP_STRIP_9");
   hSetupName->GetXaxis()->SetBinLabel(10,"GIFPP_STRIP_21");
   hSetupName->GetXaxis()->SetBinLabel(11,"GIFPP_STRIP_17");
   hSetupName->GetXaxis()->SetBinLabel(12,"GIFPP_STRIP_23");
   hSetupName->GetXaxis()->SetBinLabel(13,"GIFPP_STRIP_8");
   hSetupName->GetXaxis()->SetBinLabel(14,"GIFPP_STRIP_18");
   hSetupName->GetXaxis()->SetBinLabel(15,"GIFPP_STRIP_19");
   hSetupName->GetXaxis()->SetBinLabel(16,"GIFPP_STRIP_20");
   hSetupName->GetXaxis()->SetBinLabel(17,"GIFPP_STRIP_16");
   hSetupName->GetXaxis()->SetBinLabel(18,"GIFPP_STRIP_27");
   hSetupName->GetXaxis()->SetBinLabel(19,"GIFPP_STRIP_28");
   hSetupName->GetXaxis()->SetBinLabel(20,"GIFPP_STRIP_15");
   hSetupName->GetXaxis()->SetBinLabel(21,"GIFPP_STRIP_14");
   hSetupName->GetXaxis()->SetRange(1,32);
   hSetupName->GetXaxis()->SetLabelFont(42);
   hSetupName->GetXaxis()->SetLabelSize(0.035);
   hSetupName->GetXaxis()->SetTitleSize(0.035);
   hSetupName->GetXaxis()->SetTitleFont(42);
   hSetupName->GetYaxis()->SetTitle("Number of Run using config setup");
   hSetupName->GetYaxis()->SetLabelFont(42);
   hSetupName->GetYaxis()->SetLabelSize(0.035);
   hSetupName->GetYaxis()->SetTitleSize(0.035);
   hSetupName->GetYaxis()->SetTitleFont(42);
   hSetupName->GetZaxis()->SetLabelFont(42);
   hSetupName->GetZaxis()->SetLabelSize(0.035);
   hSetupName->GetZaxis()->SetTitleSize(0.035);
   hSetupName->GetZaxis()->SetTitleFont(42);
   hSetupName->Draw("");
   
   hSetupName = new TH1F("hSetupName","Config Setup Used",21,0,21);
   hSetupName->SetBinContent(1,57);
   hSetupName->SetBinContent(2,40);
   hSetupName->SetBinContent(3,30);
   hSetupName->SetBinContent(4,14);
   hSetupName->SetBinContent(5,8);
   hSetupName->SetBinContent(6,8);
   hSetupName->SetBinContent(7,4);
   hSetupName->SetBinContent(8,3);
   hSetupName->SetBinContent(9,3);
   hSetupName->SetBinContent(10,2);
   hSetupName->SetBinContent(11,2);
   hSetupName->SetBinContent(12,2);
   hSetupName->SetBinContent(13,2);
   hSetupName->SetBinContent(14,1);
   hSetupName->SetBinContent(15,1);
   hSetupName->SetBinContent(16,1);
   hSetupName->SetBinContent(17,1);
   hSetupName->SetBinContent(18,1);
   hSetupName->SetBinContent(19,1);
   hSetupName->SetBinContent(20,1);
   hSetupName->SetBinContent(21,1);
   hSetupName->SetEntries(183);
   hSetupName->SetFillColor(38);

   ci = TColor::GetColor("#000099");
   hSetupName->SetLineColor(ci);
   hSetupName->GetXaxis()->SetBinLabel(1,"UnknownConfig");
   hSetupName->GetXaxis()->SetBinLabel(2,"GIFPP_STRIP_22");
   hSetupName->GetXaxis()->SetBinLabel(3,"GIFPP_OYONAX_8");
   hSetupName->GetXaxis()->SetBinLabel(4,"GIFPP_OYONAX_12");
   hSetupName->GetXaxis()->SetBinLabel(5,"GIFPP_STRIP_12");
   hSetupName->GetXaxis()->SetBinLabel(6,"GIFPP_STRIP_11");
   hSetupName->GetXaxis()->SetBinLabel(7,"GIFPP_STRIP_26");
   hSetupName->GetXaxis()->SetBinLabel(8,"GIFPP_STRIP_13");
   hSetupName->GetXaxis()->SetBinLabel(9,"GIFPP_STRIP_9");
   hSetupName->GetXaxis()->SetBinLabel(10,"GIFPP_STRIP_21");
   hSetupName->GetXaxis()->SetBinLabel(11,"GIFPP_STRIP_17");
   hSetupName->GetXaxis()->SetBinLabel(12,"GIFPP_STRIP_23");
   hSetupName->GetXaxis()->SetBinLabel(13,"GIFPP_STRIP_8");
   hSetupName->GetXaxis()->SetBinLabel(14,"GIFPP_STRIP_18");
   hSetupName->GetXaxis()->SetBinLabel(15,"GIFPP_STRIP_19");
   hSetupName->GetXaxis()->SetBinLabel(16,"GIFPP_STRIP_20");
   hSetupName->GetXaxis()->SetBinLabel(17,"GIFPP_STRIP_16");
   hSetupName->GetXaxis()->SetBinLabel(18,"GIFPP_STRIP_27");
   hSetupName->GetXaxis()->SetBinLabel(19,"GIFPP_STRIP_28");
   hSetupName->GetXaxis()->SetBinLabel(20,"GIFPP_STRIP_15");
   hSetupName->GetXaxis()->SetBinLabel(21,"GIFPP_STRIP_14");
   hSetupName->GetXaxis()->SetRange(1,32);
   hSetupName->GetXaxis()->SetLabelFont(42);
   hSetupName->GetXaxis()->SetLabelSize(0.035);
   hSetupName->GetXaxis()->SetTitleSize(0.035);
   hSetupName->GetXaxis()->SetTitleFont(42);
   hSetupName->GetYaxis()->SetTitle("Number of Run using config setup");
   hSetupName->GetYaxis()->SetLabelFont(42);
   hSetupName->GetYaxis()->SetLabelSize(0.035);
   hSetupName->GetYaxis()->SetTitleSize(0.035);
   hSetupName->GetYaxis()->SetTitleFont(42);
   hSetupName->GetZaxis()->SetLabelFont(42);
   hSetupName->GetZaxis()->SetLabelSize(0.035);
   hSetupName->GetZaxis()->SetTitleSize(0.035);
   hSetupName->GetZaxis()->SetTitleFont(42);
   hSetupName->Draw("TEXT SAME");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
   gPad->Print("hSetupName_order.tex");
}
