#!/bin/sh
mkdir -p ./build
lualatex -output-directory=build -draftmode --shell-escape -file-line-error Presentation
makeglossaries -d ./build Presentation
biber --output-directory=build Presentation
lualatex -output-directory=build -draftmode --shell-escape -interaction=batchmode -file-line-error Presentation
lualatex -output-directory=build --shell-escape -interaction=batchmode -file-line-error -synctex=1 Presentation
cp ./build/Presentation.pdf ../Presentation.pdf
#latex2rtf Mythesis.tex
#gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.7 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=Compressed.pdf ./build/MyThesis.pdf
