{
//=========Macro generated from canvas: c1_n10/c1_n10
//=========  (Tue Aug 22 00:45:16 2017) by ROOT version5.34/26
   TCanvas *c1_n10 = new TCanvas("c1_n10", "c1_n10");
   gStyle->SetPaperSize(10.,10.);
   c1_n10->SetHighLightColor(2);
   c1_n10->Range(-6.8,-4.230769,38.53333,12.69231);
   c1_n10->SetFillColor(0);
   c1_n10->SetBorderMode(0);
   c1_n10->SetBorderSize(2);
   c1_n10->SetGridx();
   c1_n10->SetGridy();
   c1_n10->SetLeftMargin(0.15);
   c1_n10->SetBottomMargin(0.25);
   c1_n10->SetFrameBorderMode(0);
   c1_n10->SetFrameBorderMode(0);
   
   TH2F *hAttScanThresholdVsNrun = new TH2F("hAttScanThresholdVsNrun","Number of runs vs threshold scans",34,0,34,11,0,11);
   hAttScanThresholdVsNrun->SetBinContent(47,2);
   hAttScanThresholdVsNrun->SetBinContent(76,2);
   hAttScanThresholdVsNrun->SetBinContent(78,3);
   hAttScanThresholdVsNrun->SetBinContent(79,2);
   hAttScanThresholdVsNrun->SetBinContent(81,3);
   hAttScanThresholdVsNrun->SetBinContent(86,2);
   hAttScanThresholdVsNrun->SetBinContent(87,3);
   hAttScanThresholdVsNrun->SetBinContent(89,2);
   hAttScanThresholdVsNrun->SetBinContent(90,3);
   hAttScanThresholdVsNrun->SetBinContent(127,2);
   hAttScanThresholdVsNrun->SetBinContent(131,2);
   hAttScanThresholdVsNrun->SetBinContent(135,2);
   hAttScanThresholdVsNrun->SetBinContent(139,2);
   hAttScanThresholdVsNrun->SetBinContent(146,3);
   hAttScanThresholdVsNrun->SetBinContent(183,7);
   hAttScanThresholdVsNrun->SetBinContent(192,7);
   hAttScanThresholdVsNrun->SetBinContent(217,4);
   hAttScanThresholdVsNrun->SetBinContent(262,4);
   hAttScanThresholdVsNrun->SetBinContent(293,7);
   hAttScanThresholdVsNrun->SetBinContent(301,7);
   hAttScanThresholdVsNrun->SetBinContent(332,7);
   hAttScanThresholdVsNrun->SetBinContent(340,7);
   hAttScanThresholdVsNrun->SetBinContent(380,8);
   hAttScanThresholdVsNrun->SetBinContent(384,8);
   hAttScanThresholdVsNrun->SetBinContent(388,8);
   hAttScanThresholdVsNrun->SetBinContent(392,8);
   hAttScanThresholdVsNrun->SetBinContent(417,8);
   hAttScanThresholdVsNrun->SetBinContent(418,8);
   hAttScanThresholdVsNrun->SetBinContent(421,8);
   hAttScanThresholdVsNrun->SetBinContent(422,8);
   hAttScanThresholdVsNrun->SetBinContent(425,8);
   hAttScanThresholdVsNrun->SetBinContent(426,8);
   hAttScanThresholdVsNrun->SetBinContent(429,8);
   hAttScanThresholdVsNrun->SetBinContent(430,8);
   hAttScanThresholdVsNrun->SetEntries(34);
   hAttScanThresholdVsNrun->SetContour(20);
   hAttScanThresholdVsNrun->SetContourLevel(0,0);
   hAttScanThresholdVsNrun->SetContourLevel(1,0.4);
   hAttScanThresholdVsNrun->SetContourLevel(2,0.8);
   hAttScanThresholdVsNrun->SetContourLevel(3,1.2);
   hAttScanThresholdVsNrun->SetContourLevel(4,1.6);
   hAttScanThresholdVsNrun->SetContourLevel(5,2);
   hAttScanThresholdVsNrun->SetContourLevel(6,2.4);
   hAttScanThresholdVsNrun->SetContourLevel(7,2.8);
   hAttScanThresholdVsNrun->SetContourLevel(8,3.2);
   hAttScanThresholdVsNrun->SetContourLevel(9,3.6);
   hAttScanThresholdVsNrun->SetContourLevel(10,4);
   hAttScanThresholdVsNrun->SetContourLevel(11,4.4);
   hAttScanThresholdVsNrun->SetContourLevel(12,4.8);
   hAttScanThresholdVsNrun->SetContourLevel(13,5.2);
   hAttScanThresholdVsNrun->SetContourLevel(14,5.6);
   hAttScanThresholdVsNrun->SetContourLevel(15,6);
   hAttScanThresholdVsNrun->SetContourLevel(16,6.4);
   hAttScanThresholdVsNrun->SetContourLevel(17,6.8);
   hAttScanThresholdVsNrun->SetContourLevel(18,7.2);
   hAttScanThresholdVsNrun->SetContourLevel(19,7.6);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.895,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("Entries = 34     ");
   ptstats->SetOptStat(10);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hAttScanThresholdVsNrun->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hAttScanThresholdVsNrun);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hAttScanThresholdVsNrun->SetLineColor(ci);
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(1,"BAK STRIP(1, 100L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(2,"BAK STRIP(1, 110L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(3,"BAK STRIP(1, 130L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(4,"BAK STRIP(2, 104L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(5,"BAK STRIP(2, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(6,"BAK STRIP(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(7,"BAK STRIP(3, 104L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(8,"BAK STRIP(3, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(9,"BAK STRIP(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(10,"GLASS STRIP(1, 110L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(11,"GLASS STRIP(1, 120L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(12,"GLASS STRIP(1, 140L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(13,"GLASS STRIP(2, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(14,"GLASS STRIP(2, 218L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(15,"GLASS STRIP(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(16,"GLASS STRIP(3, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(17,"GLASS STRIP(3, 180L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(18,"GLASS STRIP(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(19,"PAD1(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(20,"PAD1(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(21,"PAD1(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(22,"PAD1(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(23,"PAD2(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(24,"PAD2(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(25,"PAD2(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(26,"PAD2(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(27,"PAD3(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(28,"PAD3(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(29,"PAD3(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(30,"PAD3(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(31,"PAD4(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(32,"PAD4(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(33,"PAD4(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(34,"PAD4(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetRange(1,64);
   hAttScanThresholdVsNrun->GetXaxis()->SetBit(TAxis::kLabelsVert);
   hAttScanThresholdVsNrun->GetXaxis()->SetLabelFont(42);
   hAttScanThresholdVsNrun->GetXaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsNrun->GetXaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsNrun->GetXaxis()->SetTitleFont(42);
   hAttScanThresholdVsNrun->GetYaxis()->SetTitle("Number of runs");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(1," 2");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(2," 3");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(3," 4");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(4," 6");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(5,"20");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(6,"23");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(7,"26");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(8,"41");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(9,"43");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(10,"48");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(11,"53");
   hAttScanThresholdVsNrun->GetYaxis()->SetRange(1,54);
   hAttScanThresholdVsNrun->GetYaxis()->SetLabelFont(42);
   hAttScanThresholdVsNrun->GetYaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsNrun->GetYaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsNrun->GetYaxis()->SetTitleFont(42);
   hAttScanThresholdVsNrun->GetZaxis()->SetLabelFont(42);
   hAttScanThresholdVsNrun->GetZaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsNrun->GetZaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsNrun->GetZaxis()->SetTitleFont(42);
   hAttScanThresholdVsNrun->Draw("COL");
   
   hAttScanThresholdVsNrun = new TH2F("hAttScanThresholdVsNrun","Number of runs vs threshold scans",34,0,34,11,0,11);
   hAttScanThresholdVsNrun->SetBinContent(47,2);
   hAttScanThresholdVsNrun->SetBinContent(76,2);
   hAttScanThresholdVsNrun->SetBinContent(78,3);
   hAttScanThresholdVsNrun->SetBinContent(79,2);
   hAttScanThresholdVsNrun->SetBinContent(81,3);
   hAttScanThresholdVsNrun->SetBinContent(86,2);
   hAttScanThresholdVsNrun->SetBinContent(87,3);
   hAttScanThresholdVsNrun->SetBinContent(89,2);
   hAttScanThresholdVsNrun->SetBinContent(90,3);
   hAttScanThresholdVsNrun->SetBinContent(127,2);
   hAttScanThresholdVsNrun->SetBinContent(131,2);
   hAttScanThresholdVsNrun->SetBinContent(135,2);
   hAttScanThresholdVsNrun->SetBinContent(139,2);
   hAttScanThresholdVsNrun->SetBinContent(146,3);
   hAttScanThresholdVsNrun->SetBinContent(183,7);
   hAttScanThresholdVsNrun->SetBinContent(192,7);
   hAttScanThresholdVsNrun->SetBinContent(217,4);
   hAttScanThresholdVsNrun->SetBinContent(262,4);
   hAttScanThresholdVsNrun->SetBinContent(293,7);
   hAttScanThresholdVsNrun->SetBinContent(301,7);
   hAttScanThresholdVsNrun->SetBinContent(332,7);
   hAttScanThresholdVsNrun->SetBinContent(340,7);
   hAttScanThresholdVsNrun->SetBinContent(380,8);
   hAttScanThresholdVsNrun->SetBinContent(384,8);
   hAttScanThresholdVsNrun->SetBinContent(388,8);
   hAttScanThresholdVsNrun->SetBinContent(392,8);
   hAttScanThresholdVsNrun->SetBinContent(417,8);
   hAttScanThresholdVsNrun->SetBinContent(418,8);
   hAttScanThresholdVsNrun->SetBinContent(421,8);
   hAttScanThresholdVsNrun->SetBinContent(422,8);
   hAttScanThresholdVsNrun->SetBinContent(425,8);
   hAttScanThresholdVsNrun->SetBinContent(426,8);
   hAttScanThresholdVsNrun->SetBinContent(429,8);
   hAttScanThresholdVsNrun->SetBinContent(430,8);
   hAttScanThresholdVsNrun->SetEntries(34);
   hAttScanThresholdVsNrun->SetContour(20);
   hAttScanThresholdVsNrun->SetContourLevel(0,0);
   hAttScanThresholdVsNrun->SetContourLevel(1,0.4);
   hAttScanThresholdVsNrun->SetContourLevel(2,0.8);
   hAttScanThresholdVsNrun->SetContourLevel(3,1.2);
   hAttScanThresholdVsNrun->SetContourLevel(4,1.6);
   hAttScanThresholdVsNrun->SetContourLevel(5,2);
   hAttScanThresholdVsNrun->SetContourLevel(6,2.4);
   hAttScanThresholdVsNrun->SetContourLevel(7,2.8);
   hAttScanThresholdVsNrun->SetContourLevel(8,3.2);
   hAttScanThresholdVsNrun->SetContourLevel(9,3.6);
   hAttScanThresholdVsNrun->SetContourLevel(10,4);
   hAttScanThresholdVsNrun->SetContourLevel(11,4.4);
   hAttScanThresholdVsNrun->SetContourLevel(12,4.8);
   hAttScanThresholdVsNrun->SetContourLevel(13,5.2);
   hAttScanThresholdVsNrun->SetContourLevel(14,5.6);
   hAttScanThresholdVsNrun->SetContourLevel(15,6);
   hAttScanThresholdVsNrun->SetContourLevel(16,6.4);
   hAttScanThresholdVsNrun->SetContourLevel(17,6.8);
   hAttScanThresholdVsNrun->SetContourLevel(18,7.2);
   hAttScanThresholdVsNrun->SetContourLevel(19,7.6);
   
   ptstats = new TPaveStats(0.78,0.895,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("Entries = 34     ");
   ptstats->SetOptStat(10);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hAttScanThresholdVsNrun->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hAttScanThresholdVsNrun);

   ci = TColor::GetColor("#000099");
   hAttScanThresholdVsNrun->SetLineColor(ci);
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(1,"BAK STRIP(1, 100L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(2,"BAK STRIP(1, 110L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(3,"BAK STRIP(1, 130L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(4,"BAK STRIP(2, 104L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(5,"BAK STRIP(2, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(6,"BAK STRIP(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(7,"BAK STRIP(3, 104L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(8,"BAK STRIP(3, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(9,"BAK STRIP(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(10,"GLASS STRIP(1, 110L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(11,"GLASS STRIP(1, 120L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(12,"GLASS STRIP(1, 140L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(13,"GLASS STRIP(2, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(14,"GLASS STRIP(2, 218L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(15,"GLASS STRIP(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(16,"GLASS STRIP(3, 106L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(17,"GLASS STRIP(3, 180L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(18,"GLASS STRIP(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(19,"PAD1(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(20,"PAD1(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(21,"PAD1(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(22,"PAD1(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(23,"PAD2(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(24,"PAD2(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(25,"PAD2(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(26,"PAD2(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(27,"PAD3(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(28,"PAD3(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(29,"PAD3(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(30,"PAD3(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(31,"PAD4(1, 150L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(32,"PAD4(1, 170L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(33,"PAD4(2, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetBinLabel(34,"PAD4(3, 250L)");
   hAttScanThresholdVsNrun->GetXaxis()->SetRange(1,64);
   hAttScanThresholdVsNrun->GetXaxis()->SetBit(TAxis::kLabelsVert);
   hAttScanThresholdVsNrun->GetXaxis()->SetLabelFont(42);
   hAttScanThresholdVsNrun->GetXaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsNrun->GetXaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsNrun->GetXaxis()->SetTitleFont(42);
   hAttScanThresholdVsNrun->GetYaxis()->SetTitle("Number of runs");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(1," 2");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(2," 3");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(3," 4");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(4," 6");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(5,"20");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(6,"23");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(7,"26");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(8,"41");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(9,"43");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(10,"48");
   hAttScanThresholdVsNrun->GetYaxis()->SetBinLabel(11,"53");
   hAttScanThresholdVsNrun->GetYaxis()->SetRange(1,54);
   hAttScanThresholdVsNrun->GetYaxis()->SetLabelFont(42);
   hAttScanThresholdVsNrun->GetYaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsNrun->GetYaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsNrun->GetYaxis()->SetTitleFont(42);
   hAttScanThresholdVsNrun->GetZaxis()->SetLabelFont(42);
   hAttScanThresholdVsNrun->GetZaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsNrun->GetZaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsNrun->GetZaxis()->SetTitleFont(42);
   hAttScanThresholdVsNrun->Draw("TEXT SAME");
   
   TPaveText *pt = new TPaveText(0.2012069,0.94,0.7987931,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("Number of runs vs threshold scans");
   pt->Draw();
   c1_n10->Modified();
   c1_n10->cd();
   c1_n10->SetSelected(c1_n10);
   gPad->Print("hAttScanThresholdVsNrun.tex");
}
