{
//=========Macro generated from canvas: c1_n10/c1_n10
//=========  (Tue Aug 22 00:45:16 2017) by ROOT version5.34/26
   TCanvas *c1_n10 = new TCanvas("c1_n10", "c1_n10");
   gStyle->SetPaperSize(10.,10.);
   c1_n10->SetHighLightColor(2);
   c1_n10->Range(-6.8,-3.076923,38.53333,9.230769);
   c1_n10->SetFillColor(0);
   c1_n10->SetBorderMode(0);
   c1_n10->SetBorderSize(2);
   c1_n10->SetGridx();
   c1_n10->SetGridy();
   c1_n10->SetLeftMargin(0.15);
   c1_n10->SetBottomMargin(0.25);
   c1_n10->SetFrameBorderMode(0);
   c1_n10->SetFrameBorderMode(0);
   
   TH2F *hAttScanThresholdVsAtt = new TH2F("hAttScanThresholdVsAtt","Attenuator value vs threshold scans",34,0,34,8,0,8);
   hAttScanThresholdVsAtt->SetBinContent(39,7);
   hAttScanThresholdVsAtt->SetBinContent(42,3);
   hAttScanThresholdVsAtt->SetBinContent(45,3);
   hAttScanThresholdVsAtt->SetBinContent(48,7);
   hAttScanThresholdVsAtt->SetBinContent(51,3);
   hAttScanThresholdVsAtt->SetBinContent(54,3);
   hAttScanThresholdVsAtt->SetBinContent(56,8);
   hAttScanThresholdVsAtt->SetBinContent(57,8);
   hAttScanThresholdVsAtt->SetBinContent(58,8);
   hAttScanThresholdVsAtt->SetBinContent(60,8);
   hAttScanThresholdVsAtt->SetBinContent(61,8);
   hAttScanThresholdVsAtt->SetBinContent(62,8);
   hAttScanThresholdVsAtt->SetBinContent(64,8);
   hAttScanThresholdVsAtt->SetBinContent(65,8);
   hAttScanThresholdVsAtt->SetBinContent(66,8);
   hAttScanThresholdVsAtt->SetBinContent(68,8);
   hAttScanThresholdVsAtt->SetBinContent(69,8);
   hAttScanThresholdVsAtt->SetBinContent(70,8);
   hAttScanThresholdVsAtt->SetBinContent(73,4);
   hAttScanThresholdVsAtt->SetBinContent(75,7);
   hAttScanThresholdVsAtt->SetBinContent(77,7);
   hAttScanThresholdVsAtt->SetBinContent(78,3);
   hAttScanThresholdVsAtt->SetBinContent(80,7);
   hAttScanThresholdVsAtt->SetBinContent(81,3);
   hAttScanThresholdVsAtt->SetBinContent(82,4);
   hAttScanThresholdVsAtt->SetBinContent(84,7);
   hAttScanThresholdVsAtt->SetBinContent(85,7);
   hAttScanThresholdVsAtt->SetBinContent(87,3);
   hAttScanThresholdVsAtt->SetBinContent(88,7);
   hAttScanThresholdVsAtt->SetBinContent(90,3);
   hAttScanThresholdVsAtt->SetBinContent(92,8);
   hAttScanThresholdVsAtt->SetBinContent(93,8);
   hAttScanThresholdVsAtt->SetBinContent(94,8);
   hAttScanThresholdVsAtt->SetBinContent(96,8);
   hAttScanThresholdVsAtt->SetBinContent(97,8);
   hAttScanThresholdVsAtt->SetBinContent(98,8);
   hAttScanThresholdVsAtt->SetBinContent(100,8);
   hAttScanThresholdVsAtt->SetBinContent(101,8);
   hAttScanThresholdVsAtt->SetBinContent(102,8);
   hAttScanThresholdVsAtt->SetBinContent(104,8);
   hAttScanThresholdVsAtt->SetBinContent(105,8);
   hAttScanThresholdVsAtt->SetBinContent(106,8);
   hAttScanThresholdVsAtt->SetBinContent(109,4);
   hAttScanThresholdVsAtt->SetBinContent(111,7);
   hAttScanThresholdVsAtt->SetBinContent(113,7);
   hAttScanThresholdVsAtt->SetBinContent(116,7);
   hAttScanThresholdVsAtt->SetBinContent(118,4);
   hAttScanThresholdVsAtt->SetBinContent(120,7);
   hAttScanThresholdVsAtt->SetBinContent(121,7);
   hAttScanThresholdVsAtt->SetBinContent(124,7);
   hAttScanThresholdVsAtt->SetBinContent(128,8);
   hAttScanThresholdVsAtt->SetBinContent(129,8);
   hAttScanThresholdVsAtt->SetBinContent(130,8);
   hAttScanThresholdVsAtt->SetBinContent(132,8);
   hAttScanThresholdVsAtt->SetBinContent(133,8);
   hAttScanThresholdVsAtt->SetBinContent(134,8);
   hAttScanThresholdVsAtt->SetBinContent(136,8);
   hAttScanThresholdVsAtt->SetBinContent(137,8);
   hAttScanThresholdVsAtt->SetBinContent(138,8);
   hAttScanThresholdVsAtt->SetBinContent(140,8);
   hAttScanThresholdVsAtt->SetBinContent(141,8);
   hAttScanThresholdVsAtt->SetBinContent(142,8);
   hAttScanThresholdVsAtt->SetBinContent(145,4);
   hAttScanThresholdVsAtt->SetBinContent(146,3);
   hAttScanThresholdVsAtt->SetBinContent(149,7);
   hAttScanThresholdVsAtt->SetBinContent(152,7);
   hAttScanThresholdVsAtt->SetBinContent(154,4);
   hAttScanThresholdVsAtt->SetBinContent(157,7);
   hAttScanThresholdVsAtt->SetBinContent(160,7);
   hAttScanThresholdVsAtt->SetBinContent(163,2);
   hAttScanThresholdVsAtt->SetBinContent(164,8);
   hAttScanThresholdVsAtt->SetBinContent(165,8);
   hAttScanThresholdVsAtt->SetBinContent(166,8);
   hAttScanThresholdVsAtt->SetBinContent(167,2);
   hAttScanThresholdVsAtt->SetBinContent(168,8);
   hAttScanThresholdVsAtt->SetBinContent(169,8);
   hAttScanThresholdVsAtt->SetBinContent(170,8);
   hAttScanThresholdVsAtt->SetBinContent(171,2);
   hAttScanThresholdVsAtt->SetBinContent(172,8);
   hAttScanThresholdVsAtt->SetBinContent(173,8);
   hAttScanThresholdVsAtt->SetBinContent(174,8);
   hAttScanThresholdVsAtt->SetBinContent(175,2);
   hAttScanThresholdVsAtt->SetBinContent(176,8);
   hAttScanThresholdVsAtt->SetBinContent(177,8);
   hAttScanThresholdVsAtt->SetBinContent(178,8);
   hAttScanThresholdVsAtt->SetBinContent(182,3);
   hAttScanThresholdVsAtt->SetBinContent(183,7);
   hAttScanThresholdVsAtt->SetBinContent(185,7);
   hAttScanThresholdVsAtt->SetBinContent(188,7);
   hAttScanThresholdVsAtt->SetBinContent(191,2);
   hAttScanThresholdVsAtt->SetBinContent(192,7);
   hAttScanThresholdVsAtt->SetBinContent(193,7);
   hAttScanThresholdVsAtt->SetBinContent(196,7);
   hAttScanThresholdVsAtt->SetBinContent(200,8);
   hAttScanThresholdVsAtt->SetBinContent(201,8);
   hAttScanThresholdVsAtt->SetBinContent(202,8);
   hAttScanThresholdVsAtt->SetBinContent(204,8);
   hAttScanThresholdVsAtt->SetBinContent(205,8);
   hAttScanThresholdVsAtt->SetBinContent(206,8);
   hAttScanThresholdVsAtt->SetBinContent(208,8);
   hAttScanThresholdVsAtt->SetBinContent(209,8);
   hAttScanThresholdVsAtt->SetBinContent(210,8);
   hAttScanThresholdVsAtt->SetBinContent(212,8);
   hAttScanThresholdVsAtt->SetBinContent(213,8);
   hAttScanThresholdVsAtt->SetBinContent(214,8);
   hAttScanThresholdVsAtt->SetBinContent(219,7);
   hAttScanThresholdVsAtt->SetBinContent(221,7);
   hAttScanThresholdVsAtt->SetBinContent(224,7);
   hAttScanThresholdVsAtt->SetBinContent(228,7);
   hAttScanThresholdVsAtt->SetBinContent(229,7);
   hAttScanThresholdVsAtt->SetBinContent(232,7);
   hAttScanThresholdVsAtt->SetBinContent(236,8);
   hAttScanThresholdVsAtt->SetBinContent(237,8);
   hAttScanThresholdVsAtt->SetBinContent(238,8);
   hAttScanThresholdVsAtt->SetBinContent(240,8);
   hAttScanThresholdVsAtt->SetBinContent(241,8);
   hAttScanThresholdVsAtt->SetBinContent(242,8);
   hAttScanThresholdVsAtt->SetBinContent(244,8);
   hAttScanThresholdVsAtt->SetBinContent(245,8);
   hAttScanThresholdVsAtt->SetBinContent(246,8);
   hAttScanThresholdVsAtt->SetBinContent(248,8);
   hAttScanThresholdVsAtt->SetBinContent(249,8);
   hAttScanThresholdVsAtt->SetBinContent(250,8);
   hAttScanThresholdVsAtt->SetBinContent(255,7);
   hAttScanThresholdVsAtt->SetBinContent(256,2);
   hAttScanThresholdVsAtt->SetBinContent(257,7);
   hAttScanThresholdVsAtt->SetBinContent(258,3);
   hAttScanThresholdVsAtt->SetBinContent(259,2);
   hAttScanThresholdVsAtt->SetBinContent(260,7);
   hAttScanThresholdVsAtt->SetBinContent(261,3);
   hAttScanThresholdVsAtt->SetBinContent(264,7);
   hAttScanThresholdVsAtt->SetBinContent(265,7);
   hAttScanThresholdVsAtt->SetBinContent(266,2);
   hAttScanThresholdVsAtt->SetBinContent(267,3);
   hAttScanThresholdVsAtt->SetBinContent(268,7);
   hAttScanThresholdVsAtt->SetBinContent(269,2);
   hAttScanThresholdVsAtt->SetBinContent(270,3);
   hAttScanThresholdVsAtt->SetBinContent(272,8);
   hAttScanThresholdVsAtt->SetBinContent(273,8);
   hAttScanThresholdVsAtt->SetBinContent(274,8);
   hAttScanThresholdVsAtt->SetBinContent(276,8);
   hAttScanThresholdVsAtt->SetBinContent(277,8);
   hAttScanThresholdVsAtt->SetBinContent(278,8);
   hAttScanThresholdVsAtt->SetBinContent(280,8);
   hAttScanThresholdVsAtt->SetBinContent(281,8);
   hAttScanThresholdVsAtt->SetBinContent(282,8);
   hAttScanThresholdVsAtt->SetBinContent(284,8);
   hAttScanThresholdVsAtt->SetBinContent(285,8);
   hAttScanThresholdVsAtt->SetBinContent(286,8);
   hAttScanThresholdVsAtt->SetBinContent(289,4);
   hAttScanThresholdVsAtt->SetBinContent(290,3);
   hAttScanThresholdVsAtt->SetBinContent(291,7);
   hAttScanThresholdVsAtt->SetBinContent(292,2);
   hAttScanThresholdVsAtt->SetBinContent(293,7);
   hAttScanThresholdVsAtt->SetBinContent(295,2);
   hAttScanThresholdVsAtt->SetBinContent(296,7);
   hAttScanThresholdVsAtt->SetBinContent(298,4);
   hAttScanThresholdVsAtt->SetBinContent(299,2);
   hAttScanThresholdVsAtt->SetBinContent(300,7);
   hAttScanThresholdVsAtt->SetBinContent(301,7);
   hAttScanThresholdVsAtt->SetBinContent(302,2);
   hAttScanThresholdVsAtt->SetBinContent(304,7);
   hAttScanThresholdVsAtt->SetBinContent(305,2);
   hAttScanThresholdVsAtt->SetBinContent(307,2);
   hAttScanThresholdVsAtt->SetBinContent(308,8);
   hAttScanThresholdVsAtt->SetBinContent(309,8);
   hAttScanThresholdVsAtt->SetBinContent(310,8);
   hAttScanThresholdVsAtt->SetBinContent(311,2);
   hAttScanThresholdVsAtt->SetBinContent(312,8);
   hAttScanThresholdVsAtt->SetBinContent(313,8);
   hAttScanThresholdVsAtt->SetBinContent(314,8);
   hAttScanThresholdVsAtt->SetBinContent(315,2);
   hAttScanThresholdVsAtt->SetBinContent(316,8);
   hAttScanThresholdVsAtt->SetBinContent(317,8);
   hAttScanThresholdVsAtt->SetBinContent(318,8);
   hAttScanThresholdVsAtt->SetBinContent(319,2);
   hAttScanThresholdVsAtt->SetBinContent(320,8);
   hAttScanThresholdVsAtt->SetBinContent(321,8);
   hAttScanThresholdVsAtt->SetBinContent(322,8);
   hAttScanThresholdVsAtt->SetEntries(179);
   hAttScanThresholdVsAtt->SetContour(20);
   hAttScanThresholdVsAtt->SetContourLevel(0,0);
   hAttScanThresholdVsAtt->SetContourLevel(1,0.4);
   hAttScanThresholdVsAtt->SetContourLevel(2,0.8);
   hAttScanThresholdVsAtt->SetContourLevel(3,1.2);
   hAttScanThresholdVsAtt->SetContourLevel(4,1.6);
   hAttScanThresholdVsAtt->SetContourLevel(5,2);
   hAttScanThresholdVsAtt->SetContourLevel(6,2.4);
   hAttScanThresholdVsAtt->SetContourLevel(7,2.8);
   hAttScanThresholdVsAtt->SetContourLevel(8,3.2);
   hAttScanThresholdVsAtt->SetContourLevel(9,3.6);
   hAttScanThresholdVsAtt->SetContourLevel(10,4);
   hAttScanThresholdVsAtt->SetContourLevel(11,4.4);
   hAttScanThresholdVsAtt->SetContourLevel(12,4.8);
   hAttScanThresholdVsAtt->SetContourLevel(13,5.2);
   hAttScanThresholdVsAtt->SetContourLevel(14,5.6);
   hAttScanThresholdVsAtt->SetContourLevel(15,6);
   hAttScanThresholdVsAtt->SetContourLevel(16,6.4);
   hAttScanThresholdVsAtt->SetContourLevel(17,6.8);
   hAttScanThresholdVsAtt->SetContourLevel(18,7.2);
   hAttScanThresholdVsAtt->SetContourLevel(19,7.6);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.895,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("Entries = 179    ");
   ptstats->SetOptStat(10);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hAttScanThresholdVsAtt->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hAttScanThresholdVsAtt);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hAttScanThresholdVsAtt->SetLineColor(ci);
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(1,"BAK STRIP(1, 100L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(2,"BAK STRIP(1, 110L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(3,"BAK STRIP(1, 130L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(4,"BAK STRIP(2, 104L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(5,"BAK STRIP(2, 106L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(6,"BAK STRIP(2, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(7,"BAK STRIP(3, 104L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(8,"BAK STRIP(3, 106L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(9,"BAK STRIP(3, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(10,"GLASS STRIP(1, 110L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(11,"GLASS STRIP(1, 120L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(12,"GLASS STRIP(1, 140L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(13,"GLASS STRIP(2, 106L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(14,"GLASS STRIP(2, 218L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(15,"GLASS STRIP(2, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(16,"GLASS STRIP(3, 106L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(17,"GLASS STRIP(3, 180L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(18,"GLASS STRIP(3, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(19,"PAD1(1, 150L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(20,"PAD1(1, 170L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(21,"PAD1(2, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(22,"PAD1(3, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(23,"PAD2(1, 150L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(24,"PAD2(1, 170L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(25,"PAD2(2, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(26,"PAD2(3, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(27,"PAD3(1, 150L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(28,"PAD3(1, 170L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(29,"PAD3(2, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(30,"PAD3(3, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(31,"PAD4(1, 150L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(32,"PAD4(1, 170L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(33,"PAD4(2, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetBinLabel(34,"PAD4(3, 250L)");
   hAttScanThresholdVsAtt->GetXaxis()->SetRange(1,64);
   hAttScanThresholdVsAtt->GetXaxis()->SetBit(TAxis::kLabelsVert);
   hAttScanThresholdVsAtt->GetXaxis()->SetLabelFont(42);
   hAttScanThresholdVsAtt->GetXaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsAtt->GetXaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsAtt->GetXaxis()->SetTitleFont(42);
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(1,"   1.5");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(2,"   3.3");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(3,"   4.6");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(4,"  10.0");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(5,"  22.0");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(6,"  46.0");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(7,"46000.0");
   hAttScanThresholdVsAtt->GetYaxis()->SetBinLabel(8,"OFF");
   hAttScanThresholdVsAtt->GetYaxis()->SetRange(1,8);
   hAttScanThresholdVsAtt->GetYaxis()->SetLabelFont(42);
   hAttScanThresholdVsAtt->GetYaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsAtt->GetYaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsAtt->GetYaxis()->SetTitleFont(42);
   hAttScanThresholdVsAtt->GetZaxis()->SetLabelFont(42);
   hAttScanThresholdVsAtt->GetZaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsAtt->GetZaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsAtt->GetZaxis()->SetTitleFont(42);
   hAttScanThresholdVsAtt->Draw("COL");
   
   TH2F *hAttScanThresholdVsAttNrunWeight = new TH2F("hAttScanThresholdVsAttNrunWeight","Attenuator value vs threshold scans",34,0,34,8,0,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(39,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(42,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(45,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(48,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(51,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(54,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(56,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(57,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(58,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(60,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(61,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(62,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(64,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(65,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(66,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(68,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(69,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(70,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(73,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(75,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(77,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(78,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(80,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(81,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(82,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(84,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(85,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(87,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(88,8);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(90,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(92,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(93,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(94,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(96,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(97,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(98,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(100,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(101,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(102,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(104,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(105,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(106,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(109,7);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(111,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(113,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(116,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(118,7);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(120,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(121,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(124,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(128,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(129,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(130,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(132,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(133,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(134,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(136,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(137,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(138,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(140,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(141,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(142,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(145,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(146,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(149,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(152,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(154,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(157,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(160,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(163,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(164,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(165,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(166,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(167,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(168,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(169,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(170,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(171,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(172,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(173,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(174,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(175,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(176,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(177,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(178,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(182,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(183,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(185,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(188,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(191,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(192,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(193,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(196,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(200,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(201,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(202,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(204,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(205,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(206,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(208,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(209,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(210,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(212,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(213,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(214,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(219,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(221,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(224,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(228,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(229,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(232,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(236,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(237,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(238,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(240,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(241,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(242,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(244,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(245,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(246,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(248,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(249,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(250,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(255,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(256,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(257,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(258,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(259,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(260,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(261,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(264,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(265,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(266,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(267,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(268,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(269,2);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(270,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(272,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(273,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(274,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(276,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(277,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(278,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(280,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(281,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(282,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(284,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(285,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(286,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(289,7);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(290,4);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(291,10);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(292,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(293,17);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(295,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(296,19);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(298,9);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(299,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(300,10);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(301,17);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(302,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(304,19);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(305,1);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(307,3);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(308,20);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(309,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(310,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(311,3);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(312,20);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(313,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(314,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(315,3);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(316,20);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(317,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(318,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(319,3);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(320,20);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(321,24);
   hAttScanThresholdVsAttNrunWeight->SetBinContent(322,24);
   hAttScanThresholdVsAttNrunWeight->SetEntries(179);

   ci = TColor::GetColor("#000099");
   hAttScanThresholdVsAttNrunWeight->SetLineColor(ci);
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(1,"BAK STRIP(1, 100L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(2,"BAK STRIP(1, 110L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(3,"BAK STRIP(1, 130L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(4,"BAK STRIP(2, 104L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(5,"BAK STRIP(2, 106L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(6,"BAK STRIP(2, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(7,"BAK STRIP(3, 104L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(8,"BAK STRIP(3, 106L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(9,"BAK STRIP(3, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(10,"GLASS STRIP(1, 110L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(11,"GLASS STRIP(1, 120L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(12,"GLASS STRIP(1, 140L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(13,"GLASS STRIP(2, 106L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(14,"GLASS STRIP(2, 218L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(15,"GLASS STRIP(2, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(16,"GLASS STRIP(3, 106L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(17,"GLASS STRIP(3, 180L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(18,"GLASS STRIP(3, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(19,"PAD1(1, 150L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(20,"PAD1(1, 170L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(21,"PAD1(2, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(22,"PAD1(3, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(23,"PAD2(1, 150L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(24,"PAD2(1, 170L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(25,"PAD2(2, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(26,"PAD2(3, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(27,"PAD3(1, 150L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(28,"PAD3(1, 170L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(29,"PAD3(2, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(30,"PAD3(3, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(31,"PAD4(1, 150L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(32,"PAD4(1, 170L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(33,"PAD4(2, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBinLabel(34,"PAD4(3, 250L)");
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetRange(1,64);
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetBit(TAxis::kLabelsVert);
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetLabelFont(42);
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsAttNrunWeight->GetXaxis()->SetTitleFont(42);
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(1,"   1.5");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(2,"   3.3");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(3,"   4.6");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(4,"  10.0");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(5,"  22.0");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(6,"  46.0");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(7,"46000.0");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetBinLabel(8,"OFF");
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetRange(1,8);
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetLabelFont(42);
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsAttNrunWeight->GetYaxis()->SetTitleFont(42);
   hAttScanThresholdVsAttNrunWeight->GetZaxis()->SetLabelFont(42);
   hAttScanThresholdVsAttNrunWeight->GetZaxis()->SetLabelSize(0.035);
   hAttScanThresholdVsAttNrunWeight->GetZaxis()->SetTitleSize(0.035);
   hAttScanThresholdVsAttNrunWeight->GetZaxis()->SetTitleFont(42);
   hAttScanThresholdVsAttNrunWeight->Draw("TEXT SAME");
   
   TPaveText *pt = new TPaveText(0.1933046,0.94,0.8066954,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("Attenuator value vs threshold scans");
   pt->Draw();
   c1_n10->Modified();
   c1_n10->cd();
   c1_n10->SetSelected(c1_n10);
   gPad->Print("hAttScanThresholdVsAtt.tex");
}
